import type { InspectionProfile } from '@/types/inspection'

const COMMON_REASONS = {
  JEV_UNCERTAIN: 'JEV 判断不確実',
  OUTSIDE_INSPECTION_ZONE: '検査ゾーン外',
  OPTION_NOT_OFFERED: '提示外の選択肢',
  JEV_DECISION: 'JEV 判断',
  WITHIN_TOLERANCE: '許容範囲内',
  REJECT_RATE_ELEVATED: '不良率 上昇',
  REJECT_RATE_HIGH: '不良率 高',
  REJECT_RATE_CRITICAL: '不良率 危険域',
  CAMERA_CONFIDENCE_LOW: 'カメラ信頼度 低下',
}

/**
 * 検査プロファイル。物体・検査属性・トリガー・映像の組を1つにまとめる。
 * 別の映像に対応するときは、ここに1件追加し public/demo/<mediaDir>/ に
 * video.mp4 と detections.json（scripts/track_video.py で生成）を置く。
 */
export const PROFILES: Record<string, InspectionProfile> = {
  'bottle-cap': {
    id: 'bottle-cap',
    name: 'ボトルキャップ検査',
    lineName: '充填ライン A',
    cameraName: 'カメラ01',
    objectLabel: 'ボトル',
    attributeLabel: 'キャップ',
    alignmentLabel: 'キャップ位置',
    okLabel: 'キャップ有',
    ngLabel: 'キャップ無',
    reasons: {
      ...COMMON_REASONS,
      ATTR_OK: 'キャップ正常',
      ATTR_OK_ALIGNMENT_LOW: 'キャップ正常（位置やや低）',
      ATTR_OK_AFTER_RECHECK: '再検査後 正常',
      ATTR_AMBIGUOUS_AFTER_RECHECK: '再検査後も判定不能',
      ATTR_MISALIGNED: 'キャップずれ',
      ATTR_LOW_CONFIDENCE: 'キャップ信頼度不足',
      ATTR_AMBIGUOUS: 'キャップ判定不能',
      ATTR_MISSING: 'キャップ欠落',
    },
    rejectAction: 'ゲート02で排出',
    misalignedScenarioName: 'キャップずれ',
    jevTask: 'bottle_cap_inspection',
    objectKey: 'bottle',
    attributeKey: 'cap',
    trigger: { kind: 'gate', axis: 'x', position: 0.5, direction: 1, zoneHalfWidth: 0.06 },
    mediaDir: 'bottle-cap',
    detectorNote: '事前追跡（bottle クラス）',
    triggerLabel: '検査ゲート',
  },
  'parcel-label': {
    id: 'parcel-label',
    name: '小包ラベル検査',
    lineName: '出荷ライン B',
    cameraName: 'カメラ02',
    objectLabel: '小包',
    attributeLabel: '配送ラベル',
    alignmentLabel: 'ラベル位置',
    okLabel: 'ラベル有',
    ngLabel: 'ラベル無',
    reasons: {
      ...COMMON_REASONS,
      ATTR_OK: 'ラベル正常',
      ATTR_OK_ALIGNMENT_LOW: 'ラベル正常（位置やや偏り）',
      ATTR_OK_AFTER_RECHECK: '再検査後 正常',
      ATTR_AMBIGUOUS_AFTER_RECHECK: '再検査後も判定不能',
      ATTR_MISALIGNED: 'ラベル位置ずれ',
      ATTR_LOW_CONFIDENCE: 'ラベル信頼度不足',
      ATTR_AMBIGUOUS: 'ラベル判定不能',
      ATTR_MISSING: 'ラベル欠落',
    },
    rejectAction: '分岐レーンへ排出',
    misalignedScenarioName: 'ラベル位置ずれ',
    jevTask: 'parcel_label_inspection',
    objectKey: 'parcel',
    attributeKey: 'shipping_label',
    trigger: { kind: 'gate', axis: 'x', position: 0.55, direction: -1, zoneHalfWidth: 0.08 },
    mediaDir: 'parcel-label',
    detectorNote: '事前追跡（文字指定: cardboard box）',
    triggerLabel: '検査ゲート',
  },
  'pcb-assembly': {
    id: 'pcb-assembly',
    name: '基板実装検査',
    lineName: '組立ライン C',
    cameraName: 'カメラ03',
    objectLabel: '基板',
    attributeLabel: '部品実装',
    alignmentLabel: '部品位置',
    okLabel: '実装済',
    ngLabel: '欠品',
    reasons: {
      ...COMMON_REASONS,
      ATTR_OK: '実装正常',
      ATTR_OK_ALIGNMENT_LOW: '実装正常（位置やや偏り）',
      ATTR_OK_AFTER_RECHECK: '再検査後 正常',
      ATTR_AMBIGUOUS_AFTER_RECHECK: '再検査後も判定不能',
      ATTR_MISALIGNED: '部品位置ずれ',
      ATTR_LOW_CONFIDENCE: '実装信頼度不足',
      ATTR_AMBIGUOUS: '実装判定不能',
      ATTR_MISSING: '部品欠品',
    },
    rejectAction: '作業者へ差し戻し',
    misalignedScenarioName: '部品位置ずれ',
    jevTask: 'pcb_assembly_inspection',
    objectKey: 'circuit_board',
    attributeKey: 'component',
    trigger: { kind: 'zone', rect: [0.25, 0.28, 0.32, 0.42], dwellSeconds: 1.5 },
    mediaDir: 'pcb-assembly',
    detectorNote: '事前追跡（文字指定: circuit board）',
    triggerLabel: '検査ステーション',
  },
}

export const PROFILE_ORDER = ['bottle-cap', 'parcel-label', 'pcb-assembly'] as const
export const DEFAULT_PROFILE_ID = 'bottle-cap'
