import type { InspectionProfile } from '@/types/inspection'

const COMMON_REASONS = {
  JEV_UNCERTAIN: 'JEV 判断不確実',
  OUTSIDE_INSPECTION_ZONE: '検査ゾーン外',
  OPTION_NOT_OFFERED: '提示外の選択肢',
  JEV_DECISION: 'JEV 判断',
  WITHIN_TOLERANCE: '許容範囲内',
  REJECT_RATE_ELEVATED: '不良率 上昇',
  REJECT_RATE_HIGH: '不良率 高',
  REJECT_RATE_CRITICAL: '不良率 危険域',
  CAMERA_CONFIDENCE_LOW: 'カメラ信頼度 低下',
}

/**
 * 検査プロファイル。物体・検査属性・トリガー・映像の組を1つにまとめる。
 * 別の映像に対応するときは、ここに1件追加し public/demo/<mediaDir>/ に
 * video.mp4 と detections.json（scripts/track_video.py で生成）を置く。
 */
export const PROFILES: Record<string, InspectionProfile> = {
  'bottle-cap': {
    id: 'bottle-cap',
    name: 'ボトルキャップ検査',
    lineName: '充填ライン A',
    cameraName: 'カメラ01',
    objectLabel: 'ボトル',
    attributeLabel: 'キャップ',
    alignmentLabel: 'キャップ位置',
    okLabel: 'キャップ有',
    ngLabel: 'キャップ無',
    reasons: {
      ...COMMON_REASONS,
      ATTR_OK: 'キャップ正常',
      ATTR_OK_ALIGNMENT_LOW: 'キャップ正常（位置やや低）',
      ATTR_OK_AFTER_RECHECK: '再検査後 正常',
      ATTR_AMBIGUOUS_AFTER_RECHECK: '再検査後も判定不能',
      ATTR_MISALIGNED: 'キャップずれ',
      ATTR_LOW_CONFIDENCE: 'キャップ信頼度不足',
      ATTR_AMBIGUOUS: 'キャップ判定不能',
      ATTR_MISSING: 'キャップ欠落',
    },
    rejectAction: 'ゲート02で排出',
    misalignedScenarioName: 'キャップずれ',
    jevTask: 'bottle_cap_inspection',
    objectKey: 'bottle',
    attributeKey: 'cap',
    trigger: { kind: 'gate', axis: 'x', position: 0.5, direction: 1, zoneHalfWidth: 0.06 },
    mediaDir: 'bottle-cap',
    detectorNote: '事前追跡（bottle クラス）',
    triggerLabel: '検査ゲート',
  },
  'parcel-label': {
    id: 'parcel-label',
    name: '小包ラベル検査',
    lineName: '出荷ライン B',
    cameraName: 'カメラ02',
    objectLabel: '小包',
    attributeLabel: '配送ラベル',
    alignmentLabel: 'ラベル位置',
    okLabel: 'ラベル有',
    ngLabel: 'ラベル無',
    reasons: {
      ...COMMON_REASONS,
      ATTR_OK: 'ラベル正常',
      ATTR_OK_ALIGNMENT_LOW: 'ラベル正常（位置やや偏り）',
      ATTR_OK_AFTER_RECHECK: '再検査後 正常',
      ATTR_AMBIGUOUS_AFTER_RECHECK: '再検査後も判定不能',
      ATTR_MISALIGNED: 'ラベル位置ずれ',
      ATTR_LOW_CONFIDENCE: 'ラベル信頼度不足',
      ATTR_AMBIGUOUS: 'ラベル判定不能',
      ATTR_MISSING: 'ラベル欠落',
    },
    rejectAction: '分岐レーンへ排出',
    misalignedScenarioName: 'ラベル位置ずれ',
    jevTask: 'parcel_label_inspection',
    objectKey: 'parcel',
    attributeKey: 'shipping_label',
    trigger: { kind: 'gate', axis: 'x', position: 0.55, direction: -1, zoneHalfWidth: 0.08 },
    mediaDir: 'parcel-label',
    detectorNote: '事前追跡（文字指定: cardboard box）',
    triggerLabel: '検査ゲート',
  },
  'pcb-assembly': {
    id: 'pcb-assembly',
    name: '基板実装検査',
    lineName: '組立ライン C',
    cameraName: 'カメラ03',
    objectLabel: '基板',
    attributeLabel: '部品実装',
    alignmentLabel: '部品位置',
    okLabel: '実装済',
    ngLabel: '欠品',
    reasons: {
      ...COMMON_REASONS,
      ATTR_OK: '実装正常',
      ATTR_OK_ALIGNMENT_LOW: '実装正常（位置やや偏り）',
      ATTR_OK_AFTER_RECHECK: '再検査後 正常',
      ATTR_AMBIGUOUS_AFTER_RECHECK: '再検査後も判定不能',
      ATTR_MISALIGNED: '部品位置ずれ',
      ATTR_LOW_CONFIDENCE: '実装信頼度不足',
      ATTR_AMBIGUOUS: '実装判定不能',
      ATTR_MISSING: '部品欠品',
    },
    rejectAction: '作業者へ差し戻し',
    misalignedScenarioName: '部品位置ずれ',
    jevTask: 'pcb_assembly_inspection',
    objectKey: 'circuit_board',
    attributeKey: 'component',
    trigger: { kind: 'zone', rect: [0.25, 0.35, 0.5, 0.45], dwellSeconds: 1.5 },
    mediaDir: 'pcb-assembly',
    detectorNote: '事前追跡（文字指定: circuit board）',
    triggerLabel: '検査ステーション',
  },
}

PROFILES['fill-level'] = {
  id: 'fill-level',
  name: '充填量検査',
  lineName: '充填ライン D',
  cameraName: 'カメラ04',
  objectLabel: 'ボトル',
  attributeLabel: '充填量',
  alignmentLabel: '液面の傾き',
  okLabel: '規格内',
  ngLabel: '規格外',
  reasons: {
    ...COMMON_REASONS,
    FILL_OK: '充填量 規格内',
    FILL_OK_AFTER_RECHECK: '再計測後 規格内',
    FILL_MARGINAL: '充填量 境界域（再計測）',
    FILL_MARGINAL_AFTER_RECHECK: '再計測後も境界域',
    UNDERFILL: '充填不足',
    OVERFILL: '過充填',
    MEASUREMENT_UNCERTAIN: '液面を特定できず',
    ATTR_OK: '充填量 規格内',
    ATTR_MISSING: '充填不足',
    ATTR_MISALIGNED: '充填量 境界域',
    ATTR_LOW_CONFIDENCE: '計測信頼度不足',
    ATTR_AMBIGUOUS: '液面を特定できず',
  },
  rejectAction: '排出レーンへ振分',
  misalignedScenarioName: '充填量ばらつき',
  jevTask: 'fill_level_inspection',
  objectKey: 'bottle',
  attributeKey: 'fill_level',
  trigger: { kind: 'gate', axis: 'x', position: 0.68, direction: 1, zoneHalfWidth: 0.07 },
  mediaDir: 'fill-level',
  detectorNote: '合成トラック',
  triggerLabel: '計測ゲート',
  measurement: { key: 'fill_level', label: '充填率', unit: '%', target: 0.8, tolerance: 0.04 },
  syntheticFeed: 'filling',
}

PROFILES['fall-detection'] = {
  id: 'fall-detection',
  name: '転倒検知',
  lineName: '病棟 廊下 A',
  cameraName: 'カメラ05',
  objectLabel: '人物',
  attributeLabel: '転倒',
  alignmentLabel: '胴の角度',
  okLabel: '正常',
  ngLabel: '転倒',
  reasons: {
    ...COMMON_REASONS,
    SCENE_ALERT: '転倒を確認（床上に滞留）',
    SCENE_WATCH: '転倒の疑い（経過観察）',
    SCENE_UNCERTAIN: '姿勢を特定できず',
    SCENE_NORMAL: '異常なし',
    ATTR_OK: '異常なし',
    ATTR_MISSING: '転倒を確認',
    ATTR_MISALIGNED: '転倒の疑い',
    ATTR_LOW_CONFIDENCE: '姿勢信頼度不足',
    ATTR_AMBIGUOUS: '姿勢を特定できず',
  },
  rejectAction: '職員へ通報',
  misalignedScenarioName: '転倒の疑い増加',
  jevTask: 'fall_detection',
  objectKey: 'person',
  attributeKey: 'fall',
  trigger: { kind: 'state', confirmSeconds: 0.5 },
  analyzer: 'fall',
  mediaDir: 'fall-detection',
  detectorNote: '事前追跡（骨格 17 点 + 追跡）',
  triggerLabel: '状態監視',
  syntheticFeed: 'none',
  decisionLabels: { PASS: '異常なし', RECHECK: '経過観察', REJECT: '転倒 警報', HUMAN_REVIEW: '要確認' },
  kpiLabels: { total: '判定回数', pass: '異常なし', reject: '転倒警報', yield: '異常なし率', throughputUnit: '件/分' },
}

PROFILES['crosswalk'] = {
  id: 'crosswalk',
  name: '横断歩道 安全監視',
  lineName: '市道 交差点 B',
  cameraName: 'カメラ06',
  objectLabel: '歩行者',
  attributeLabel: '危険',
  alignmentLabel: '接近度',
  okLabel: '安全',
  ngLabel: '危険',
  reasons: {
    ...COMMON_REASONS,
    SCENE_ALERT: '横断中の歩行者に走行車両が接近',
    SCENE_WATCH: '車両接近（注意）',
    SCENE_UNCERTAIN: '追跡が不安定',
    SCENE_NORMAL: '安全に横断',
    ATTR_OK: '安全に横断',
    ATTR_MISSING: '危険な横断',
    ATTR_MISALIGNED: '車両接近（注意）',
    ATTR_LOW_CONFIDENCE: '追跡信頼度不足',
    ATTR_AMBIGUOUS: '追跡が不安定',
  },
  rejectAction: '歩行者警告灯・信号制御',
  misalignedScenarioName: '接近車両 増加',
  jevTask: 'crosswalk_safety',
  objectKey: 'pedestrian',
  attributeKey: 'collision_risk',
  trigger: { kind: 'state', confirmSeconds: 0.4 },
  analyzer: 'crosswalk',
  zones: [
    { id: 'crosswalk', label: '横断歩道', kind: 'crosswalk', polygon: [[0.12, 0.66], [0.88, 0.46], [0.92, 0.56], [0.16, 0.78]] },
    { id: 'wait-near', label: '待機ゾーン', kind: 'waiting', polygon: [[0.0, 0.7], [0.12, 0.66], [0.16, 0.78], [0.36, 0.9], [0.36, 1.0], [0.0, 1.0]] },
    { id: 'wait-far', label: '待機ゾーン', kind: 'waiting', polygon: [[0.88, 0.46], [1.0, 0.43], [1.0, 0.6], [0.92, 0.56]] },
    { id: 'near-far', label: '横断歩道付近（車道）', kind: 'near', polygon: [[0.0, 0.56], [0.55, 0.45], [0.88, 0.46], [0.12, 0.66], [0.0, 0.62]] },
    { id: 'near-close', label: '横断歩道付近（車道）', kind: 'near', polygon: [[0.16, 0.78], [0.92, 0.56], [1.0, 0.6], [1.0, 1.0], [0.42, 1.0]] },
  ],
  classLabels: { person: '歩行者', bicycle: '自転車', car: '車両', truck: 'トラック', bus: 'バス', motorcycle: '二輪車' },
  mediaDir: 'crosswalk',
  detectorNote: '事前追跡（人・自転車・車両）',
  triggerLabel: '横断監視',
  syntheticFeed: 'none',
  decisionLabels: { PASS: '安全に横断', RECHECK: '注意', REJECT: '危険 警報', HUMAN_REVIEW: '要確認' },
  kpiLabels: { total: '横断回数', pass: '安全横断', reject: '危険警報', yield: '安全横断率', throughputUnit: '人/分' },
}

PROFILES['road-scan'] = {
  id: 'road-scan',
  name: '路面損傷スキャン',
  lineName: '市道 巡回車 C',
  cameraName: 'カメラ07（車載）',
  objectLabel: '損傷',
  attributeLabel: '重症度',
  alignmentLabel: '路面位置',
  okLabel: '軽微',
  ngLabel: '要補修',
  reasons: {
    ...COMMON_REASONS,
    ATTR_OK: '軽微（記録のみ）',
    ATTR_OK_ALIGNMENT_LOW: '軽微（記録のみ）',
    ATTR_OK_AFTER_RECHECK: '再計測後 軽微',
    ATTR_AMBIGUOUS_AFTER_RECHECK: '再計測後も中程度（点検要請）',
    ATTR_MISALIGNED: '中程度（再計測）',
    ATTR_LOW_CONFIDENCE: '中程度（再計測）',
    ATTR_AMBIGUOUS: '大きめ（点検要請）',
    ATTR_MISSING: '大型（要補修）',
  },
  rejectAction: '補修依頼を起票',
  misalignedScenarioName: '中程度の損傷 増加',
  jevTask: 'road_damage_scan',
  objectKey: 'pothole',
  attributeKey: 'severity',
  trigger: { kind: 'gate', axis: 'y', position: 0.62, direction: 1, zoneHalfWidth: 0.1 },
  classLabels: { pothole: 'ポットホール' },
  mediaDir: 'road-scan',
  detectorNote: '事前追跡（ポットホール専用モデル）',
  triggerLabel: '計測ライン',
  syntheticFeed: 'none',
  severityFromArea: { fullArea: 0.08, label: '面積比' },
  odometer: { kmh: 20 },
  decisionLabels: { PASS: '軽微（記録）', RECHECK: '再計測', REJECT: '要補修（起票）', HUMAN_REVIEW: '点検要請' },
  kpiLabels: { total: '判定した損傷', pass: '軽微', reject: '要補修', yield: '軽微率', throughputUnit: '件/分' },
}

export const PROFILE_ORDER = ['bottle-cap', 'parcel-label', 'pcb-assembly', 'fill-level', 'fall-detection', 'crosswalk', 'road-scan'] as const
export const DEFAULT_PROFILE_ID = 'bottle-cap'
