/**
 * Builds the portable single-file distributions from src/:
 *
 *   dist/mathcat.js        — ESM, plain JavaScript, zero dependencies
 *   dist/mathcat.global.js — classic <script> build, exposes globalThis.mathcat
 *   dist/mathcat.d.ts      — TypeScript declarations for both
 *
 * Uses Node's built-in TypeScript type stripping (node:module), so the build
 * itself has zero dependencies too. Run with: npm run build
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { stripTypeScriptTypes } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'));
const MODULES = ['vec2', 'vec3', 'quat', 'mat4', 'color', 'random', 'easing'];

/** Strips types and module syntax, leaving a plain script body. */
const toScriptBody = (source) => {
  let code = stripTypeScriptTypes(source, { mode: 'strip' });
  code = code
    .split('\n')
    .filter((line) => !/^\s*import\b/.test(line))
    .map((line) => line.replace(/^export /, ''))
    .join('\n');
  // Doc comments whose subject was a stripped type end up followed by a
  // blank line; drop them so the generated file reads cleanly.
  code = code.replace(/(^|\n)\/\*\*[\s\S]*?\*\/[ \t]*\n(?=\s*\n)/g, '$1');
  // Type stripping blanks annotations in place; collapse the leftover gaps.
  // Safe here because the kernel sources contain no string literals.
  code = code
    .replace(/ +(?=[,)])/g, '')
    .replace(/\) +=>/g, ') =>')
    .replace(/ +$/gm, '');
  return code.replace(/\n{3,}/g, '\n\n').trim();
};

const typesSource = readFileSync(path.join(root, 'src', 'types.ts'), 'utf8');
const epsilon = typesSource.match(/const EPSILON = ([^;]+);/)[1];

const namespaces = MODULES.map((name) => {
  const source = readFileSync(path.join(root, 'src', `${name}.ts`), 'utf8');
  const body = toScriptBody(source);
  const exported = [...body.matchAll(/^const (\w+) =/gm)].map((m) => m[1]);
  return { name, body, exported };
});

const banner = `/**
 * mathcat v${pkg.version} — ${pkg.description}
 * Generated from src/ by scripts/build.mjs. Do not edit by hand.
 *
 * The usage contract: every operation is op(out, a, b) — writes into the
 * caller-owned \`out\`, returns it, never allocates. \`out\` may alias an
 * input. Keep call sites monomorphic (one array type per code path).
 */`;

const core = [
  `/** The tolerance used by approximate comparisons. */`,
  `const EPSILON = ${epsilon};`,
  ...namespaces.map(
    ({ name, body, exported }) =>
      `\nconst ${name} = (() => {\n${body}\n\nreturn Object.freeze({ ${exported.join(', ')} });\n})();`,
  ),
].join('\n');

mkdirSync(path.join(root, 'dist'), { recursive: true });

const esm = `${banner}\n${core}\n\nexport { EPSILON, ${MODULES.join(', ')} };\n`;
writeFileSync(path.join(root, 'dist', 'mathcat.js'), esm);

const globalBuild = `${banner}\n(() => {\n${core}\n\nglobalThis.mathcat = Object.freeze({ EPSILON, ${MODULES.join(', ')} });\n})();\n`;
writeFileSync(path.join(root, 'dist', 'mathcat.global.js'), globalBuild);

const dts = `/**
 * mathcat v${pkg.version} — type declarations for dist/mathcat.js and
 * dist/mathcat.global.js. Generated by scripts/build.mjs. Do not edit.
 */

/** Caller-owned flat numeric storage accepted by every operation. */
export type NumberArray = number[] | Float32Array | Float64Array;
/** A 2-component vector: [x, y] */
export type Vec2 = NumberArray;
/** A 3-component vector: [x, y, z] */
export type Vec3 = NumberArray;
/** A quaternion: [x, y, z, w] */
export type Quat = NumberArray;
/** A 4x4 matrix, column-major (WebGL/WebGPU convention), 16 elements */
export type Mat4 = NumberArray;
/** An RGB color with components in [0, 1]: [r, g, b] */
export type Color = NumberArray;
/** A function returning a uniform float in [0, 1). */
export type Rng = () => number;

/** The tolerance used by approximate comparisons. */
export declare const EPSILON: number;

export declare namespace vec2 {
  function create(): Vec2;
  function set(out: Vec2, x: number, y: number): Vec2;
  function copy(out: Vec2, a: Vec2): Vec2;
  function add(out: Vec2, a: Vec2, b: Vec2): Vec2;
  function subtract(out: Vec2, a: Vec2, b: Vec2): Vec2;
  function scale(out: Vec2, a: Vec2, s: number): Vec2;
  function dot(a: Vec2, b: Vec2): number;
  function cross(a: Vec2, b: Vec2): number;
  function length(a: Vec2): number;
  function squaredLength(a: Vec2): number;
  function distance(a: Vec2, b: Vec2): number;
  function normalize(out: Vec2, a: Vec2): Vec2;
  function lerp(out: Vec2, a: Vec2, b: Vec2, t: number): Vec2;
  function rotate(out: Vec2, a: Vec2, origin: Vec2, rad: number): Vec2;
  function equals(a: Vec2, b: Vec2, epsilon?: number): boolean;
}

export declare namespace vec3 {
  function create(): Vec3;
  function set(out: Vec3, x: number, y: number, z: number): Vec3;
  function copy(out: Vec3, a: Vec3): Vec3;
  function add(out: Vec3, a: Vec3, b: Vec3): Vec3;
  function subtract(out: Vec3, a: Vec3, b: Vec3): Vec3;
  function multiply(out: Vec3, a: Vec3, b: Vec3): Vec3;
  function scale(out: Vec3, a: Vec3, s: number): Vec3;
  function scaleAndAdd(out: Vec3, a: Vec3, b: Vec3, s: number): Vec3;
  function dot(a: Vec3, b: Vec3): number;
  function cross(out: Vec3, a: Vec3, b: Vec3): Vec3;
  function length(a: Vec3): number;
  function squaredLength(a: Vec3): number;
  function distance(a: Vec3, b: Vec3): number;
  function normalize(out: Vec3, a: Vec3): Vec3;
  function negate(out: Vec3, a: Vec3): Vec3;
  function lerp(out: Vec3, a: Vec3, b: Vec3, t: number): Vec3;
  function transformQuat(out: Vec3, a: Vec3, q: Quat): Vec3;
  function transformMat4(out: Vec3, a: Vec3, m: Mat4): Vec3;
  function equals(a: Vec3, b: Vec3, epsilon?: number): boolean;
}

export declare namespace quat {
  function create(): Quat;
  function identity(out: Quat): Quat;
  function set(out: Quat, x: number, y: number, z: number, w: number): Quat;
  function copy(out: Quat, a: Quat): Quat;
  function setAxisAngle(out: Quat, axis: Vec3, rad: number): Quat;
  function fromEuler(out: Quat, x: number, y: number, z: number): Quat;
  function multiply(out: Quat, a: Quat, b: Quat): Quat;
  function conjugate(out: Quat, a: Quat): Quat;
  function dot(a: Quat, b: Quat): number;
  function normalize(out: Quat, a: Quat): Quat;
  function slerp(out: Quat, a: Quat, b: Quat, t: number): Quat;
  function equals(a: Quat, b: Quat, epsilon?: number): boolean;
}

export declare namespace mat4 {
  function create(): Mat4;
  function identity(out: Mat4): Mat4;
  function copy(out: Mat4, a: Mat4): Mat4;
  function multiply(out: Mat4, a: Mat4, b: Mat4): Mat4;
  function compose(out: Mat4, translation: Vec3, rotation: Quat, scale: Vec3): Mat4;
  function invert(out: Mat4, a: Mat4): Mat4;
  function perspective(out: Mat4, fovy: number, aspect: number, near: number, far: number): Mat4;
  function lookAt(out: Mat4, eye: Vec3, target: Vec3, up: Vec3): Mat4;
  function transpose(out: Mat4, a: Mat4): Mat4;
  function equals(a: Mat4, b: Mat4, epsilon?: number): boolean;
}

export declare namespace color {
  function create(): Color;
  function set(out: Color, r: number, g: number, b: number): Color;
  function fromHex(out: Color, hex: number): Color;
  function toHex(a: Color): number;
  function fromHsl(out: Color, h: number, s: number, l: number): Color;
  function lerp(out: Color, a: Color, b: Color, t: number): Color;
  function srgbToLinear(out: Color, a: Color): Color;
  function linearToSrgb(out: Color, a: Color): Color;
}

export declare namespace random {
  function createRng(seed: number): Rng;
  function range(rng: Rng, min: number, max: number): number;
  function intRange(rng: Rng, min: number, max: number): number;
  function onCircle(out: Vec2, rng: Rng): Vec2;
  function onSphere(out: Vec3, rng: Rng): Vec3;
  function inSphere(out: Vec3, rng: Rng): Vec3;
}

export declare namespace easing {
  function linear(t: number): number;
  function quadIn(t: number): number;
  function quadOut(t: number): number;
  function quadInOut(t: number): number;
  function cubicIn(t: number): number;
  function cubicOut(t: number): number;
  function cubicInOut(t: number): number;
  function expoOut(t: number): number;
  function elasticOut(t: number): number;
  function bounceOut(t: number): number;
  function smoothstep(edge0: number, edge1: number, x: number): number;
  function clamp(x: number, min: number, max: number): number;
  function mix(a: number, b: number, t: number): number;
  function remap(x: number, inMin: number, inMax: number, outMin: number, outMax: number): number;
}
`;
writeFileSync(path.join(root, 'dist', 'mathcat.d.ts'), dts);

console.log('dist/mathcat.js, dist/mathcat.global.js, dist/mathcat.d.ts written');
