// Bundles the whole visualisation into one self-contained HTML file that runs
// straight off the filesystem — no server, no build tooling, no dependencies.
//
//   node build.mjs            → sound-reactive-shapes.html
//   node build.mjs out.html   → out.html
//
// The only thing still fetched at runtime is three.js from jsDelivr, which the
// import map resolves; jsDelivr sends CORS headers, so it loads from file:// too.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const read = (p) => fs.readFileSync(path.join(here, p), 'utf8');

const SHADERS = [
  'vertex.glsl', 'sdf-functions.glsl', 'sdf-marcher.glsl', 'scalar-marcher.glsl',
  'platonic-functions.glsl', 'moving-scalar-functions.glsl', 'rim-lighting.glsl',
  'lighting.glsl', 'deform.glsl', 'fragment-sdf.glsl', 'fragment-platonic.glsl',
  'fragment-scalar.glsl', 'fragment-moving.glsl', 'fragment-form.glsl',
];

// Embed as a template literal rather than JSON so the GLSL stays readable in the
// output. GLSL contains none of these sequences, but escaping them keeps the
// build correct regardless of what the shaders grow into.
const asTemplate = (s) => '`' + s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';

const shaderBlock = `const __SHADER_SOURCES = {\n${
  SHADERS.map((n) => `  ${JSON.stringify(n)}: ${asTemplate(read(`shaders/${n}`))},`).join('\n')
}\n};\nglobalThis.__SHADER_SOURCES = __SHADER_SOURCES;`;

// The three modules become one script. Only their cross-imports are dropped —
// the bare `three` specifiers still resolve through the import map.
function inlineModule(file, { dropImports = [] } = {}) {
  let src = read(file);
  for (const spec of dropImports) {
    const re = new RegExp(`^import\\s+\\{[^}]*\\}\\s+from\\s+['"]${spec}['"];\\s*$`, 'm');
    if (!re.test(src)) throw new Error(`${file}: expected an import of ${spec} to remove`);
    src = src.replace(re, '');
  }
  // `export` only ever prefixes a declaration in these files; strip the keyword
  // so everything lands in one shared module scope.
  return src.replace(/^export\s+(?=(const|class|function)\b)/gm, '');
}

const envmapJs = inlineModule('js/oklch-envmap.js');
const audioJs  = inlineModule('js/audio.js');
const mainJs   = inlineModule('js/main.js', {
  dropImports: ['./oklch-envmap.js', './audio.js'],
});

for (const [name, src] of [['audio.js', audioJs], ['main.js', mainJs], ['oklch-envmap.js', envmapJs]]) {
  if (/^\s*(import|export)\b/m.test(src.replace(/^import .* from 'three.*$/gm, ''))) {
    throw new Error(`${name}: leftover import/export would break the inlined bundle`);
  }
}

// Take the page shell from index.html and swap its external references for the
// inlined equivalents, so the two versions cannot drift apart.
let html = read('index.html');

html = html.replace(
  /  <link rel="stylesheet" href="\.\/css\/ui\.css" \/>\n/,
  `  <style>\n${read('css/ui.css')}  </style>\n`,
);
if (html.includes('css/ui.css')) throw new Error('stylesheet link was not replaced');

const bundle = [
  '  <script type="module">',
  shaderBlock,
  envmapJs,
  audioJs,
  mainJs,
  '  <\/script>',
].join('\n');

html = html.replace(/  <script type="module" src="\.\/js\/main\.js"><\/script>\n/, bundle + '\n');
if (html.includes('js/main.js')) throw new Error('module script tag was not replaced');

html = html.replace('<title>Sound-reactive shapes</title>',
  '<title>Sound-reactive shapes</title>\n  <!-- Generated by build.mjs — edit the sources in js/ css/ shaders/, not this file. -->');

const out = path.join(here, process.argv[2] || 'sound-reactive-shapes.html');
fs.writeFileSync(out, html);
console.log(`${path.relative(process.cwd(), out)}  ${(html.length / 1024).toFixed(0)} KB`);
