// Everything you hear is generated by oscillators and noise buffers built at
// runtime. There are no audio files in this project -- including the reverb,
// whose impulse response is synthesised from decaying noise on startup.

const PENTATONIC = [220.00, 261.63, 293.66, 329.63, 392.00, 440.00, 523.25, 587.33];

export class AudioEngine {
  constructor() {
    this.ready = false;
    this.enabled = true;
    this.windAmount = 0.35;
    this._nextPluck = 4;
  }

  start() {
    if (this.ready) return;
    const Ctx = window.AudioContext || window.webkitAudioContext;
    if (!Ctx) return;
    const ctx = new Ctx();
    this.ctx = ctx;

    this.master = ctx.createGain();
    this.master.gain.value = 0.0;
    const comp = ctx.createDynamicsCompressor();
    comp.threshold.value = -18;
    comp.knee.value = 20;
    comp.ratio.value = 4;
    comp.attack.value = 0.004;
    comp.release.value = 0.25;
    this.master.connect(comp).connect(ctx.destination);
    this.master.gain.linearRampToValueAtTime(0.9, ctx.currentTime + 2.5);

    // --- reverb -----------------------------------------------------------
    this.reverb = ctx.createConvolver();
    this.reverb.buffer = this._impulse(3.4, 2.6);
    this.reverbGain = ctx.createGain();
    this.reverbGain.gain.value = 0.9;
    this.reverb.connect(this.reverbGain).connect(this.master);

    this.dry = ctx.createGain();
    this.dry.gain.value = 1;
    this.dry.connect(this.master);

    this.noiseBuffer = this._noise(4, 'white');
    this.brownBuffer = this._noise(6, 'brown');

    this._buildWind();
    this._buildDrone();

    this.ready = true;
  }

  resume() { if (this.ctx && this.ctx.state === 'suspended') this.ctx.resume(); }

  // -----------------------------------------------------------------------

  _noise(seconds, kind) {
    const ctx = this.ctx;
    const len = Math.floor(ctx.sampleRate * seconds);
    const buf = ctx.createBuffer(2, len, ctx.sampleRate);
    for (let ch = 0; ch < 2; ch++) {
      const d = buf.getChannelData(ch);
      let last = 0;
      for (let i = 0; i < len; i++) {
        const w = Math.random() * 2 - 1;
        if (kind === 'brown') {
          last = (last + 0.02 * w) / 1.02;
          d[i] = last * 3.2;
        } else {
          d[i] = w;
        }
      }
    }
    return buf;
  }

  _impulse(seconds, decay) {
    const ctx = this.ctx;
    const len = Math.floor(ctx.sampleRate * seconds);
    const buf = ctx.createBuffer(2, len, ctx.sampleRate);
    for (let ch = 0; ch < 2; ch++) {
      const d = buf.getChannelData(ch);
      for (let i = 0; i < len; i++) {
        const t = i / len;
        // a few discrete early reflections then a smooth tail
        let s = (Math.random() * 2 - 1) * Math.pow(1 - t, decay);
        if (i < ctx.sampleRate * 0.09 && Math.random() < 0.0016) s += (Math.random() * 2 - 1) * 0.8;
        d[i] = s * 0.55;
      }
    }
    return buf;
  }

  _src(buffer, loop = false) {
    const s = this.ctx.createBufferSource();
    s.buffer = buffer;
    s.loop = loop;
    return s;
  }

  _env(gain, t0, a, d, peak) {
    gain.gain.cancelScheduledValues(t0);
    gain.gain.setValueAtTime(0.0001, t0);
    gain.gain.linearRampToValueAtTime(peak, t0 + a);
    gain.gain.exponentialRampToValueAtTime(0.0001, t0 + a + d);
  }

  _send(node, wet) {
    node.connect(this.dry);
    const g = this.ctx.createGain();
    g.gain.value = wet;
    node.connect(g).connect(this.reverb);
  }

  // --- ambience ----------------------------------------------------------

  _buildWind() {
    const ctx = this.ctx;
    const src = this._src(this.brownBuffer, true);
    const bp = ctx.createBiquadFilter();
    bp.type = 'bandpass';
    bp.frequency.value = 420;
    bp.Q.value = 0.55;
    const hp = ctx.createBiquadFilter();
    hp.type = 'highpass';
    hp.frequency.value = 120;
    const g = ctx.createGain();
    g.gain.value = 0.0;
    src.connect(bp).connect(hp).connect(g);
    this._send(g, 0.5);
    src.start();

    // slow gusting
    const lfo = ctx.createOscillator();
    lfo.frequency.value = 0.055;
    const lfoG = ctx.createGain();
    lfoG.gain.value = 260;
    lfo.connect(lfoG).connect(bp.frequency);
    lfo.start();

    this.windGain = g;
    this.windFilter = bp;
  }

  _buildDrone() {
    const ctx = this.ctx;
    const g = ctx.createGain();
    g.gain.value = 0.0;
    const lp = ctx.createBiquadFilter();
    lp.type = 'lowpass';
    lp.frequency.value = 340;
    lp.Q.value = 3;
    g.connect(lp);
    this._send(lp, 0.8);

    [55, 82.41, 110, 164.81].forEach((f, i) => {
      const o = ctx.createOscillator();
      o.type = i % 2 ? 'triangle' : 'sine';
      o.frequency.value = f * (1 + (i - 1.5) * 0.0016);
      const og = ctx.createGain();
      og.gain.value = [0.5, 0.28, 0.22, 0.1][i];
      o.connect(og).connect(g);
      o.start();
    });

    const lfo = ctx.createOscillator();
    lfo.frequency.value = 0.037;
    const lg = ctx.createGain();
    lg.gain.value = 180;
    lfo.connect(lg).connect(lp.frequency);
    lfo.start();

    g.gain.linearRampToValueAtTime(0.10, ctx.currentTime + 6);
    this.droneGain = g;
  }

  update(dt, { speed = 0, tension = 0 } = {}) {
    if (!this.ready) return;
    const t = this.ctx.currentTime;
    const target = 0.035 + this.windAmount * 0.055 + Math.min(speed / 8, 1) * 0.03;
    this.windGain.gain.setTargetAtTime(target, t, 0.4);
    this.droneGain.gain.setTargetAtTime(0.085 + tension * 0.09, t, 1.5);

    this._nextPluck -= dt;
    if (this._nextPluck <= 0) {
      this._nextPluck = 7 + Math.random() * 11;
      this.pluck(PENTATONIC[(Math.random() * PENTATONIC.length) | 0] * (Math.random() < 0.3 ? 0.5 : 1));
    }
  }

  // --- one-shots ---------------------------------------------------------

  pluck(freq, gainScale = 1) {
    if (!this.ready) return;
    const ctx = this.ctx, t = ctx.currentTime;
    const car = ctx.createOscillator();
    car.type = 'sine';
    car.frequency.value = freq;
    const mod = ctx.createOscillator();
    mod.type = 'sine';
    mod.frequency.value = freq * 2.01;
    const modG = ctx.createGain();
    modG.gain.setValueAtTime(freq * 1.6, t);
    modG.gain.exponentialRampToValueAtTime(1, t + 0.5);
    mod.connect(modG).connect(car.frequency);
    const g = ctx.createGain();
    this._env(g, t, 0.006, 2.6, 0.10 * gainScale);
    car.connect(g);
    this._send(g, 1.2);
    car.start(t); mod.start(t);
    car.stop(t + 3.2); mod.stop(t + 3.2);
  }

  chime(index = 0) {
    if (!this.ready) return;
    const base = PENTATONIC[index % PENTATONIC.length];
    this.pluck(base * 2, 1.6);
    setTimeout(() => this.pluck(base * 3, 1.0), 190);
    setTimeout(() => this.pluck(base, 1.2), 420);
  }

  step(strength = 0.5) {
    if (!this.ready) return;
    const ctx = this.ctx, t = ctx.currentTime;
    const s = this._src(this.noiseBuffer);
    s.playbackRate.value = 0.8 + Math.random() * 0.5;
    const bp = ctx.createBiquadFilter();
    bp.type = 'bandpass';
    bp.frequency.value = 700 + Math.random() * 900;
    bp.Q.value = 1.4;
    const g = ctx.createGain();
    this._env(g, t, 0.002, 0.07 + Math.random() * 0.04, 0.05 * strength);
    s.connect(bp).connect(g);
    this._send(g, 0.35);
    s.start(t);
    s.stop(t + 0.3);
  }

  sniff() {
    if (!this.ready) return;
    const ctx = this.ctx, t = ctx.currentTime;
    const s = this._src(this.noiseBuffer);
    const bp = ctx.createBiquadFilter();
    bp.type = 'bandpass';
    bp.Q.value = 3.2;
    bp.frequency.setValueAtTime(700, t);
    bp.frequency.exponentialRampToValueAtTime(2100, t + 0.11);
    const g = ctx.createGain();
    this._env(g, t, 0.012, 0.10, 0.05);
    s.connect(bp).connect(g);
    this._send(g, 0.2);
    s.start(t); s.stop(t + 0.4);
  }

  dig() {
    if (!this.ready) return;
    const ctx = this.ctx, t = ctx.currentTime;
    const s = this._src(this.noiseBuffer);
    s.playbackRate.value = 0.6 + Math.random() * 0.6;
    const bp = ctx.createBiquadFilter();
    bp.type = 'bandpass';
    bp.Q.value = 1.1;
    bp.frequency.setValueAtTime(300 + Math.random() * 200, t);
    bp.frequency.linearRampToValueAtTime(1500, t + 0.14);
    const g = ctx.createGain();
    this._env(g, t, 0.004, 0.15, 0.055);
    s.connect(bp).connect(g);
    this._send(g, 0.3);
    s.start(t); s.stop(t + 0.4);
  }

  /** @param {{distant?:boolean, pitch?:number, delay?:number}} o */
  bark(o = {}) {
    if (!this.ready) return;
    const ctx = this.ctx;
    const t = ctx.currentTime + (o.delay || 0);
    const distant = !!o.distant;
    const pitch = o.pitch || 1;
    const out = ctx.createGain();
    out.gain.value = distant ? 0.30 : 1.0;

    if (distant) {
      const lp = ctx.createBiquadFilter();
      lp.type = 'lowpass';
      lp.frequency.value = 620;
      out.connect(lp);
      this._send(lp, 3.2);
    } else {
      this._send(out, 0.8);
    }

    // voiced part: a fast downward glide through a formant
    const osc = ctx.createOscillator();
    osc.type = 'sawtooth';
    osc.frequency.setValueAtTime(480 * pitch, t);
    osc.frequency.exponentialRampToValueAtTime(150 * pitch, t + 0.11);
    const form = ctx.createBiquadFilter();
    form.type = 'bandpass';
    form.frequency.setValueAtTime(1100, t);
    form.frequency.exponentialRampToValueAtTime(420, t + 0.15);
    form.Q.value = 2.2;
    const og = ctx.createGain();
    this._env(og, t, 0.006, 0.17, 0.22);
    osc.connect(form).connect(og).connect(out);
    osc.start(t); osc.stop(t + 0.45);

    // breath / transient
    const s = this._src(this.noiseBuffer);
    const bp = ctx.createBiquadFilter();
    bp.type = 'bandpass';
    bp.frequency.setValueAtTime(2200, t);
    bp.frequency.exponentialRampToValueAtTime(700, t + 0.09);
    bp.Q.value = 1.1;
    const ng = ctx.createGain();
    this._env(ng, t, 0.003, 0.09, 0.14);
    s.connect(bp).connect(ng).connect(out);
    s.start(t); s.stop(t + 0.4);

    // body thump
    const sub = ctx.createOscillator();
    sub.type = 'sine';
    sub.frequency.setValueAtTime(150 * pitch, t);
    sub.frequency.exponentialRampToValueAtTime(70, t + 0.13);
    const sg = ctx.createGain();
    this._env(sg, t, 0.004, 0.14, 0.16);
    sub.connect(sg).connect(out);
    sub.start(t); sub.stop(t + 0.35);
  }

  howl(distant = true) {
    if (!this.ready) return;
    const ctx = this.ctx, t = ctx.currentTime;
    const osc = ctx.createOscillator();
    osc.type = 'sawtooth';
    osc.frequency.setValueAtTime(210, t);
    osc.frequency.linearRampToValueAtTime(330, t + 0.5);
    osc.frequency.linearRampToValueAtTime(300, t + 1.5);
    osc.frequency.linearRampToValueAtTime(180, t + 2.4);
    const f = ctx.createBiquadFilter();
    f.type = 'bandpass';
    f.frequency.value = 800;
    f.Q.value = 3.5;
    const lp = ctx.createBiquadFilter();
    lp.type = 'lowpass';
    lp.frequency.value = distant ? 700 : 2200;
    const g = ctx.createGain();
    this._env(g, t, 0.35, 2.2, distant ? 0.10 : 0.2);
    osc.connect(f).connect(lp).connect(g);
    this._send(g, distant ? 3.0 : 1.2);
    osc.start(t); osc.stop(t + 3.0);
  }

  whoosh() {
    if (!this.ready) return;
    const ctx = this.ctx, t = ctx.currentTime;
    const s = this._src(this.noiseBuffer);
    const bp = ctx.createBiquadFilter();
    bp.type = 'bandpass';
    bp.Q.value = 1.6;
    bp.frequency.setValueAtTime(180, t);
    bp.frequency.exponentialRampToValueAtTime(2600, t + 0.55);
    const g = ctx.createGain();
    this._env(g, t, 0.05, 0.9, 0.07);
    s.connect(bp).connect(g);
    this._send(g, 2.0);
    s.start(t); s.stop(t + 1.4);
  }

  resonance(freq = 98) {
    if (!this.ready) return;
    const ctx = this.ctx, t = ctx.currentTime;
    [1, 2.02, 3.01, 4.4].forEach((m, i) => {
      const o = ctx.createOscillator();
      o.type = 'sine';
      o.frequency.value = freq * m;
      const g = ctx.createGain();
      this._env(g, t, 0.02 + i * 0.03, 2.4 - i * 0.4, 0.12 / (i + 1));
      o.connect(g);
      this._send(g, 2.2);
      o.start(t); o.stop(t + 3.2);
    });
  }

  heartbeat() {
    if (!this.ready) return;
    const ctx = this.ctx, t = ctx.currentTime;
    const thump = (at, amp) => {
      const o = ctx.createOscillator();
      o.type = 'sine';
      o.frequency.setValueAtTime(72, at);
      o.frequency.exponentialRampToValueAtTime(38, at + 0.16);
      const g = ctx.createGain();
      this._env(g, at, 0.008, 0.20, amp);
      o.connect(g);
      this._send(g, 0.4);
      o.start(at); o.stop(at + 0.4);
    };
    thump(t, 0.22);
    thump(t + 0.30, 0.15);
  }

  fadeOut(seconds = 4) {
    if (!this.ready) return;
    this.master.gain.setTargetAtTime(0.0001, this.ctx.currentTime, seconds / 4);
  }
}
